version: "3.3"

services:

  prof_ruano_server:
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - variables.env
    build:
      context: ./
    ports:
      - "4000:8000"
    volumes:
      - ./landing:/landing
      - prof_ruano:/tmp/prof_ruano_db
      - media:/landing/media
    container_name: prof_ruano_server
    depends_on:
      - prof_ruano_db
    entrypoint: ["/bin/bash", "run.sh"]

  prof_ruano_db:
    env_file:
      - variables.env
    image: postgres:13.1
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      interval: 10s
      timeout: 45s
      retries: 10
    expose:
      - "5656"
    volumes:
      - backups:/var/lib/postgresql/data
    container_name: prof_ruano_db
    command: -p 5656
    ports:
      - "5656:5656"

volumes:
  prof_ruano:
  media:
  backups:
